# Generated by Django 5.1.6 on 2025-03-17 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de perfil')),
                ('store_name', models.CharField(help_text='Nombre que se mostrará en tu perfil de vendedor', max_length=100, verbose_name='Nombre de la tienda')),
                ('slogan', models.CharField(blank=True, help_text='Una frase corta que describa tu tienda', max_length=200, null=True, verbose_name='Slogan')),
                ('description', models.TextField(help_text='Describe tu tienda y los productos que vendes', verbose_name='Descripción')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de vendedor',
                'verbose_name_plural': 'Perfiles de vendedores',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=20, verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de cierre')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='seller_profiles.sellerprofile')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['day'],
                'unique_together': {('profile', 'day')},
            },
        ),
    ]
