# Generated by Django 5.1.6 on 2025-03-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de cierre'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
    ]
