# Generated by Django 5.1.6 on 2025-03-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profiles', '0002_alter_schedule_options_schedule_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ingresa tu número de WhatsApp con código de país (ej: 573001234567)', max_length=15, null=True, verbose_name='WhatsApp'),
        ),
    ]
