# Generated by Django 5.1.6 on 2025-02-10 06:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto', max_length=255, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('Comida', 'Comida'), ('Ropa', 'Ropa'), ('Tecnología', 'Tecnología'), ('Libros', 'Libros'), ('Otros', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('description', models.TextField(help_text='Describe tu producto detalladamente', verbose_name='Descripción')),
                ('quantity', models.PositiveIntegerField(help_text='Debe ser mayor a 0', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('condition', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Buen estado', 'Buen estado')], max_length=50, verbose_name='Estado')),
                ('location', models.CharField(blank=True, help_text='Lugar de entrega en el campus', max_length=255, null=True, verbose_name='Ubicación')),
                ('image', models.ImageField(help_text='Imagen del producto', upload_to='products/', verbose_name='Imagen')),
                ('payment_method', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=20, verbose_name='Método de pago')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de cuenta válido', regex='^\\d{10,20}$')], verbose_name='Número de cuenta')),
                ('account_type', models.CharField(blank=True, choices=[('Nequi', 'Nequi'), ('Bancolombia', 'Bancolombia')], max_length=50, null=True, verbose_name='Tipo de cuenta')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('tags', models.CharField(blank=True, help_text='Separa las etiquetas con comas', max_length=255, verbose_name='Etiquetas')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'), models.Index(fields=['available'], name='products_pr_availab_21d9ca_idx')],
            },
        ),
    ]
