# Generated by Django 5.1.6 on 2025-02-19 18:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-published_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Calificación de 0 a 5 estrellas', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de cuenta válido', regex='^\\d{10,20}$')], verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Nequi', 'Nequi'), ('Bancolombia', 'Bancolombia')], max_length=50, null=True, verbose_name='Tipo de cuenta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Ropa', 'Ropa'), ('Tecnología', 'Tecnología'), ('Libros', 'Libros'), ('Otros', 'Otros')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Buen estado', 'Buen estado')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Describe tu producto detalladamente', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Imagen del producto', upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, help_text='Lugar de entrega en el campus', max_length=255, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nombre del producto', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='payment_method',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Debe ser mayor a 0', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Separa las etiquetas con comas', max_length=255, verbose_name='Etiquetas'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available'], name='products_pr_availab_21d9ca_idx'),
        ),
    ]
