# Generated by Django 5.1.6 on 2025-03-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.CharField(blank=True, choices=[('Panadería', 'Panadería'), ('Galletas', 'Galletas'), ('Repostería', 'Repostería'), ('Frutas', 'Frutas'), ('Frituras', 'Frituras'), ('Dulces', 'Dulces'), ('Helados', 'Helados'), ('Snacks', 'Snacks'), ('Comida rápida', 'Comida rápida'), ('Otros', 'Otros')], max_length=50, null=True, verbose_name='Tipo de Comida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Buen estado', 'Buen estado')], max_length=50, null=True, verbose_name='Estado'),
        ),
    ]
