# Generated by Django 5.1.6 on 2025-03-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Comida', 'Comida'), ('Ropa', 'Ropa'), ('Tecnología', 'Tecnología'), ('Libros', 'Libros'), ('Otros', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('food_type', models.CharField(blank=True, choices=[('Panadería', 'Panadería'), ('Galletas', 'Galletas'), ('Repostería', 'Repostería'), ('Frutas', 'Frutas'), ('Frituras', 'Frituras'), ('Dulces', 'Dulces'), ('Helados', 'Helados'), ('Snacks', 'Snacks'), ('Comida rápida', 'Comida rápida'), ('Otros', 'Otros')], max_length=50, null=True, verbose_name='Tipo de Comida')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_14b9c0_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='food_type',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
    ]
