# Generated by Django 5.1.6 on 2025-03-16 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Ropa', 'Ropa'), ('Tecnología', 'Tecnología'), ('Libros', 'Libros'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Buen estado', 'Buen estado')], max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.CharField(blank=True, choices=[('Panadería', 'Panadería'), ('Galletas', 'Galletas'), ('Repostería', 'Repostería'), ('Frutas', 'Frutas'), ('Frituras', 'Frituras'), ('Dulces', 'Dulces'), ('Helados', 'Helados'), ('Snacks', 'Snacks'), ('Comida rápida', 'Comida rápida'), ('Otros', 'Otros')], max_length=50, null=True, verbose_name='Tipo de Comida'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
