# Generated by Django 5.1.6 on 2025-03-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Comida', 'Comida'), ('Ropa', 'Ropa'), ('Tecnología', 'Tecnología'), ('Libros', 'Libros'), ('Otros', 'Otros')], max_length=50, null=True, verbose_name='Categoría'),
        ),
    ]
