# Generated by Django 5.1.6 on 2025-04-23 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='Consulta en lenguaje natural del usuario', verbose_name='Consulta')),
                ('processed_keywords', models.TextField(blank=True, help_text='Palabras clave extraídas por Gemini API', null=True, verbose_name='Palabras clave procesadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consulta')),
                ('success', models.BooleanField(default=True, verbose_name='Procesamiento exitoso')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta de chatbot',
                'verbose_name_plural': 'Consultas de chatbot',
                'ordering': ['-created_at'],
            },
        ),
    ]
